# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root

development:
  <<: *default
  host: localhost
  #socket: /tmp/mysql.sock
  database: my_home_development

staging:
  <<: *default
  pool: 20
  host: localhost
  database: my_home_staging

production:
  pool: 50
  host: localhost
  database: my_home_production
