# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password:

development:
  <<: *default
  host: localhost
  #socket: /tmp/mysql.sock
  database: my_home_development

staging:
  <<: *default
  host: localhost
  database: my_home_staging
  username: root
  password: 

production:
  <<: *default
  database: db/production.sqlite3
